common:
    env: dev
    ingress:
        host: tavla.dev.entur.no
    configmap:
        data:
            GOOGLE_PROJECT_ID: ent-tavla-dev
            NODE_ENV: development
            NEXT_PUBLIC_POSTHOG_TOKEN: 'phc_nUrbtV6i5kD39V6hxZ1j6eLtaphJY38sklcUuIDEby4'
            NEXT_PUBLIC_BASE_URL: 'https://tavla.dev.entur.no'
