common:
    env: prd
    ingress:
        host: tavla.entur.no
    configmap:
        data:
            GOOGLE_PROJECT_ID: ent-tavla-prd
            NODE_ENV: production
            NEXT_PUBLIC_POSTHOG_TOKEN: 'phc_Iu3qLYA1btPuImlxyuQajuvQUoxp6ShId7wwvaMZGJb'
            NEXT_PUBLIC_BASE_URL: 'https://tavla.entur.no'
