name: cd/backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  docker-push:
    uses: entur/gha-docker/.github/workflows/push.yml@v1.2.3
    with:
      environment: prd
      context: backend
      image_name: tavla/backend

  helm-deploy-dev:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      chart: backend/helm/backend
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      release_name: backend


  helm-deploy-prd:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: prd
      chart: backend/helm/backend
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      release_name: backend
