name: cd/frontend/dev

on:
  workflow_dispatch:

jobs:
  docker-push:
    uses: entur/gha-docker/.github/workflows/push.yml@v1.2.3
    with:
      context: tavla
      image_name: tavla/frontend

  helm-deploy-dev:
    needs: [docker-push]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      chart: tavla/helm/tavla
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
